# Generated by Django 5.0.1 on 2024-02-14 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsAggregate",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("link", models.TextField()),
                ("description", models.TextField()),
                ("creator", models.TextField()),
                ("publication_date", models.CharField(max_length=255)),
                ("media_url", models.TextField()),
                ("media_description", models.TextField()),
                ("media_credit", models.TextField()),
                ("categories", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "news_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.newssite"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
