# Generated by Django 5.0.1 on 2024-03-17 05:02

import neclicense.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neclicense", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="uploads/nec/%Y/%m/%d/",
                validators=[neclicense.models.validate_file_extension],
            ),
        ),
    ]
