# Generated by Django 5.0.1 on 2024-03-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_seocontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="seocontent",
            name="keywords",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
