# Generated by Django 5.0.1 on 2024-03-17 04:59

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_seocontent_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="uploads/material/%Y/%m/%d/",
                validators=[content.models.validate_file_extension],
            ),
        ),
    ]
