# Generated by Django 5.0.1 on 2025-02-25 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_engineeringprojectcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic",
                to="content.chapter",
            ),
        ),
    ]
